anakryiko/retsnoop

- src/Makefile
Make sure calib_feat.skel.h is already there when compile retsnoop.c.
Signed-off-by: Thinker Lee <thinker.li@gmail.com>
> retsnoop: depends on calib_feat

- sidecar/src/main.rs
- src/addr2line.c
The sidecar is going to provide various features.  To support that,
every request have to be prefixed with a verb to designate what
function it requests.
This change is on the top of PR3.
> retsnoop: sidecar accepts verbs in requests

- sidecar/Cargo.lock
- sidecar/Cargo.toml
- sidecar/src/main.rs
- src/addr2line.c
- src/addr2line.h
- src/retsnoop.c
By prefixing ':' before the name of a compile unit, all functions defined in the compile unit will be added to the specified list of globs.  For example, giving '-a :path/to/XXX.c', all functions defined in XXX.c will be added to the allow list.
> Add functions defined in compile unit(s) to the list of globs

- src/Makefile
- src/calib_feat.bpf.c
- src/mass_attach.bpf.c
Currently retsnoop doesn't work in my arm64 machine as it reports
`uname -a` as aarch64,
Also update the instruction pointer accessor to use some BTF goodness,
as arm uses `user_pt_regs` instead of `pt_regs`.
BTW, thanks for this tool! It's incredibly useful and works great! ❤️ Will throw
away all my custom bpftrace scripts to do half of what this tool does. Would
send you a #thanks if I could :)
> Fix arm64 build

- src/retsnoop.c
Just playing with this after link from HN, and error confused me by saying -p PRESET. Probably ought to fix that :)
I'm not adamant on `-c ?`, feel free to only take the first patch -- it's just the first way I could think of to get the list without looking at the code. Turned out there were less than I thought so it's probably not very useful for most people right now, but assuming more presets get added it could become handy?
> fix default error message keyword for presets (and add -c ? for list)

- src/Makefile
This will make it easier to package retsnoop in distributions
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>
> Add 'make install' target

- sidecar/Cargo.toml
Two of the dependencies are outdated; retsnoop builds fine with the latest on Fedora 37 and rawhide x86_64
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>
> Bump dependencies

- src/Makefile
When building `retsnoop` in Linux distributions, distribution-wide settings are passed via `CFLAGS`. Use this if set and provide a default otherwise.
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>
> use system CFLAGS if set

- src/calib_feat.bpf.c
- src/mass_attach.bpf.c
----------
newer kernels with BPF_FUNC_get_func_ip can get a correct value with bpf_get_func_ip, but for older kernels we look directly at the hardware ip reg and it appears to only be off by one on x86 architectures.
Make the `- 1` we use to find function pointers architecture dependant to fix non-x86 runs.
Tested by forcing has_bpf_get_func_ip to false.
Fixes: #32
------------------
Took me a bit more than a week, sorry for the delay.
We don't seem to have any arch-specific code in retsnoop itself (most of it is in libbpf/src/bpf_tracing.h which is part of libbpf) so I wasn't sure what to use, but PT_REGS_IP is actually defined in bpf_tracing.h so we can use the defines set there. If you can think of something better happy to adjust anything.
I've tested on x86_64 with a newer kernel by …
> retsnoop: fix non-x86 IP reg when no BPF_FUNC_get_func_ip

- src/retsnoop.c
io_uring is now in the root of Linux repo, so add it into linux_dirs table.
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
> retsnoop: add io_uring/ linux_dir and resort all the others

- .github/workflows/release.yml
- scripts/gh-label-release-assets.sh
Same as for [veristat](https://github.com/libbpf/veristat/pull/5). Minor differences include:
- Script under `BSD-2-Clause` rather than dual license, to match with the rest of the repository
- Using `$(CFLAGS)` and not `$(EXTRA_CFLAGS)` to pass `--static`
Note that compiling the binary on arm64 takes much longer in the case of retsnoop, apparently because of the Rust tool: it took 20 minutes for my test run (vs. ~2min for amd64).
Test release [available here](https://github.com/qmonnet/retsnoop/releases/tag/test01).
> Add release workflow for shipping binaries and combined sources

- src/addr2line.c
- src/addr2line.h
- src/retsnoop.c
In child_driver when addr2line binary is getting prepared, it's getting executed with an empty envp. This could lead to issues if the environment is messed up and retsnoop was started with envp, specifically constructed to fix this (think of libraries visibility for example).
Do an extra mile and carry around the original provided envp to pass it into fexecve.
> retsnoop: Pass the real envp to the sidecar

- src/mass_attach.bpf.c
- src/mass_attacher.c
- src/retsnoop.h
Dynamically determine number of CPUs and size BPF-side data accordingly. This removes previously hard-coded limitation of supporting machines with only up to 256 cores.
> retsnoop: remove hard-coded maximum of 256 CPUs supported

- src/retsnoop.bpf.c
- src/retsnoop.h
If we decide that function is returning 32-bit integer (which is a default case when we can't get BTF information about the function, so this would be common right now for kernel module functions), we should truncate actual returned value (captured as u64) to 32-bit u32 before doing the comparisons inside IS_ERR_VALUE32().
This potentially could break some cases in fentry/fexit (-F) mode with pointer-returning functions (which is explained in the comment inside IS_ERR_VALUE32()), but those should be determined as pointer-returning from BTF information, and will be handled with IS_ERR_VALUE().
Reported-by: Maxim Samoylov <max7255@meta.com>
> retsnoop: fix sign extension failure logic

- .github/workflows/release.yml
According to Github Actions, this should allow to trigger the workflow manually. Let's see.
Cc: Quentin Monnet <quentin@isovalent.com>
> ci: mark release workflow as `workflow_dispatch`

- .github/workflows/build.yml
- src/Makefile
Bpftool expects users to pass additional compilation flags via `EXTRA_CFLAGS`, not via `CFLAGS`. This is because when compiled from the kernel repo, `CFLAGS` are usually overwritten by the build system.
When we build retsnoop with `CFLAGS=--static`, the static flag is passed down to bpftool's `Makefile`. Then we hit an issue: `--static` is ignored for feature probing at build time, but taken into account for the build itself. Under certain conditions this results in a discrepency and bpftool's `Makefile` believes LLVM support is available (given it tested without the `--static` flag) whereas it is not set up for static builds.
Let's address this by passing retsnoop's `CFLAGS` via bpftool's `EXTRA_CFLAGS`, and resetting its `CFLAGS`. We must pass the `CFLAGS` to the "make" invocation …
> bpftool: Pass additional compile flags as EXTRA_CFLAGS, not CFLAGS

- sidecar/Cargo.lock
- sidecar/Cargo.toml
- sidecar/src/main.rs
This change updates the addr2line dependency to 0.21. To prevent version mismatch, also update gimli to 0.28, as it's part of addr2line's public API surface and needs to match what retsnoop itself uses, because objects are exchanged.
> sidecar: Update addr2line dependency to 0.21

- .github/workflows/build.yml
- src/Makefile
(This is the first patch from #56)
The link rule normally uses LDFLAGS and not CFLAGS.
For backwards compatibility though keep both as compilers will just ignore compile flags when linking.
Also note that LDFLAGS would also apply to the bpftool build, which might cause problems if some flags intended for retsnoop cannot link with it (e.g. -static for bpftool requires more libraries to be available as .a); if that becomes a problem we might need a way to differentiate the two in the future.
> Makefile: use LDFLAGS for linking

- src/Makefile
Hi!
I'm still using retsnoop once in a while and needed it at home (nixos), so figured I'd package it there.
First commit is mostly unrelated -- the link command ought to use LDFLAGS and not CFLAGS. Keeping CFLAGS doesn't really hurt but shouldn't be required so I removed it, happy to use both flags instead as long as LDFLAGS are added.
The second commit is a bit more complicated: Nixos requires the build to not use internet, so I need to build the addr2line sidecar crate with a frozen cargo command independently of the rest -- that's internal nixos mess and I'm not expecting any help here, but I also had problem with the sidecar ld command in the past (#31 -- actually that'd need an extra subst for `-` -> `_`, I wonder if make has a better syntax for this, sure couldn't find it... At …
> Makefile: Update variables for package builds with external artifacts

- src/Makefile
(This is a follow-up on #56 -- it contains #56 itself as that'd conflict so leaving it as draft fo now)
If the SIDECAR variable has been overriden then running cargo is not
useful nor desired:
define a DEFAULT_SIDECAR variable we can compare against and only add
the `$(SIDECAR)::` rebuild rule if SIDECAR has the default value.
------------
>> The last commit is complete garbage, but I couldn't come up with a way to flag that I don't want to rebuild the sidecar (the :: make target will always try to run cargo and that'll fail for me); I think I'll just patch it on the nixos side but bringing it up here if you have a better idea.
>
> yeah, this is not good for "normal" build path. What we can do, perhaps, is to have DEFAULT_SIDECAR vs SIDECAR that can be overridden, and if they don't match, …
> Makefile: Do not rebuild the sidecar if not the default path

- sidecar/Cargo.toml
We're updating gimli / addr2line / object in Fedora to prepare for getting blazesym packaged, retsnoop can/should be updated to match
> Bump gimli stack

- src/env.c
- src/env.h
- src/logic.c
- src/retsnoop.bpf.c
- src/retsnoop.c
Make it possible to have only function trace mode without emitting call stack traces, and vice versa. For function trace-only mode switch the default to allow capturing success stacks, as that's the most typical assumption. For call stack mode still default to emitting erroring stacks only, by default. Allow to force it one way or the other with -Sn or -Sy/-S arguments.
> retsnoop: make func call trace and call stack modes independent

- src/fnargs.c
- src/logic.c
- src/logic.h
- src/retsnoop.bpf.c
- src/retsnoop.h
Idle threads all have PID 0, one idle thread per each CPU. This screws up retsnoop's logic around using PID as a unique session ID. So for idle threads, use -(1 + CPU ID) as a session (session ID 0 will be reserved as invalid).
> retsnoop: handle idle threads properly

- src/logic.c
Fix a condition for detecting missing function args for collapsed leaf entry. Also make sure we handle fake records added by add_missing_records_msg() correctly.
> logic: fix handling of partial fnargs/ctxargs data

- src/retsnoop.bpf.c
This is suboptimal, but also, depending on compiler version, can generate code that would look like an infinite loop to the BPF verifier, apparently.
Closes: https://github.com/anakryiko/retsnoop/issues/79
Reported-by: Daniel Hodges <hodges.daniel.scott@gmail.com>
> retsnoop: avoid checking `if (sess->defunct)` twice

- src/retsnoop.bpf.c
Fix only filter first 4 characters of process/thread names with -n (--comm) or -N (--no-comm) args.
> retsnoop: fix handling -n (--comm) and -N (--no-comm) filtering

- sidecar/Cargo.lock
- sidecar/Cargo.toml
- sidecar/src/main.rs
Use "derive" features of clap 4 to declare and parse addr2line command line arguments.
Resolves: #77 
Link: https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html
Link: https://simoncw.com/posts/learning-rust-from-clap2-2-clap4/
> sidecar: migrate from clap 2 to clap 4

- src/powerpc/vmlinux.h
- src/riscv/vmlinux.h
Previous run failed on ppc64le architecture, so we were missing powerpc and riscv64 versions. Updating them now as well.
> vmlinux.h: regenerate vmlinux.h again, with feeling

- sidecar/Cargo.lock
- sidecar/Cargo.toml
- sidecar/src/main.rs
This is requested by the Rust SIG so we don't need to bring in deprecated dependencies into EPEL 10 and then maintain it for the lifetime of RHEL 10 (a decade plus)
> Replace the deprecated memmap with the maintained memmap2

- src/fnargs.c
- src/retsnoop.bpf.c
- src/retsnoop.c
- src/retsnoop.h
Rename and refactor bits of function args capture:
- some naming adjustment;
- retsnoop.bpf.c: stack pointer fetching should always work, so no need to guard it with arch checks;
- retsnoop.h: avoid data declaration in a header, instead hard-code arm64-specific register name resolution logic;
- fnargs.c: use stack alignment in bytes, instead of mask;
> fnargs: follow up refactoring
